MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"  # Specifies the architecture (Faster R-CNN)
  RPN:
    PRE_NMS_TOPK_TEST: 6000  # Number of top proposals before NMS during testing
    POST_NMS_TOPK_TEST: 1000  # Number of top proposals after NMS during testing
  ROI_HEADS:
    NAME: "Res5ROIHeads"  # Name of the ROI Heads component, indicating ResNet Stage 5 is used

DATASETS:
  TRAIN: ("coco_train_data_x",)  # Placeholder for the training dataset
  TEST: ("coco_val_data_x",)  # Placeholder for the validation dataset

SOLVER:
  IMS_PER_BATCH: 16  # Batch size for training
  BASE_LR: 0.02  # Learning rate
  STEPS: (60000, 80000)  # Steps for learning rate decay
  MAX_ITER: 90000  # Total number of iterations for training

INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)  # Multi-scale training sizes for input images

VERSION: 2  # Indicates versioning for clarity or compatibility
